language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_install:
  - pecl install https://pecl.php.net/get/swoole-1.9.0.tgz
  - travis_retry composer self-update

install:
  - composer install

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run
